default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 123456
  port: 5432
  pool: 50

development:
  <<: *default
  database: carsWebsite_development

test:
  <<: *default
  database: carsWebsite_test

production:
  <<: *default
  pool: 5
  database: carsWebsite_production
  username: postgres
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
  host: 127.0.0.1
